version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: student_management_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: student_management
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - student_management_network

networks:
  student_management_network:
    driver: bridge

volumes:
  mysql_data: